// GET /api/certificates/[certificateId]/file/personalized
//
// RD-CERT-PHOTO-02 — the SAME certificate, rendered with the attendee's own photo.
//
// ═══ WHY THIS IS A SIBLING AND NOT A BRANCH IN /file ═════════════════════════
// `/file` is the emailed download link, the organizer dashboard's download, and the path
// the ZIP/backfill jobs rely on. It streams the STORED ARTIFACT and must keep doing exactly
// that, byte-for-byte, for every caller that has ever used it. Personalization is a
// different product behaviour — a render that is never stored — so it gets its own URL and
// leaves the artifact endpoint untouched.
//
// ═══ THIS IS NOT A WEAKER DOOR ═══════════════════════════════════════════════
// Every gate `/file` applies is applied here, in the same order, from the same helpers:
// per-IP throttle → id validation → certificate exists AND has an artifact → revoked is
// blocked for everyone → organizer bypass by Bearer → the organizer's download settings
// (enabled / allowAttendee / requireVerification, the latter satisfied by EITHER the
// short-lived Certificate Center capability OR the permanent emailed token, compared the
// same disjoint way).
//
// A certificate photo GRANT is deliberately NOT accepted here. A grant is the WRITE
// credential for a photo and is minted straight after a public lookup; it is not, and must
// not become, a way to download a PDF (see photo/session/route.ts). The only credentials
// this route knows are the ones `/file` already honours.
//
// ═══ THE CANONICAL ARTIFACT IS NEVER TOUCHED ═════════════════════════════════
// `renderCertificateOnDemand` writes no certificate field. `fileKey`, `fileSize`, the
// `data` snapshot, the issuance timestamp and the verification token are all untouched — two
// people downloading the same certificate id, one with a photo and one without, get two
// different files and the SAME issued certificate.
//
// ═══ RD-CERT-PERSONALIZED-CACHE (P1) ═════════════════════════════════════════
// This route used to render a PDF on EVERY request, with `Cache-Control: no-store`, so the
// cost scaled with DOWNLOADS rather than with certificates: one attendee refreshing ten times
// cost ten pdf-lib renders (~155 ms CPU each). At 10k attendees that is a live-event CPU
// contention risk on a public endpoint.
//
// The personalised PDF is now persisted under a key derived from the certificate AND the
// photo it embeds, then served through the ordinary signed-URL mechanism. Rendering happens
// at most once per (certificate, photo version).
//
// WHY A SEPARATE KEY AND NOT `fileKey`: lib/certificates/artifact.ts deliberately refuses to
// store a personalised render as the canonical artifact — that object is the certificate AS
// ISSUED, and one attendee's photo must never become the bytes another download serves.

import { NextRequest, NextResponse } from 'next/server'
import { adminAuth }                 from '@/lib/firebase/admin'
import { getCertificate, incrementCertificateDownload, getSettings } from '@/lib/certificates/firestore'
import { defaultCertificateSettings } from '@/lib/certificates/types'
import { looksLikeDownloadCapability, verifyCertificateDownloadCapability } from '@/lib/certificates/downloadCapability'
import { isValidCertificateId }      from '@/lib/certificates/id'
import { renderCertificateOnDemand } from '@/lib/certificates/generate'
import { storage, buildObjectKey }   from '@/features/platform-storage'
import { ARTIFACT_SIGNED_URL_TTL_S } from '@/lib/certificates/constants'
import { createHash }                from 'crypto'
import { captureError }              from '@/lib/monitoring/sentry'
import { timingSafeEqualStr }        from '@/lib/security/timingSafe'
import { getClientIp }               from '@/lib/rateLimit'
import { RATE_POLICY, checkPolicy }  from '@/lib/rateLimit/policies'

type Params = { params: Promise<{ certificateId: string }> }

/**
 * Hands the request back to the canonical artifact endpoint, query string intact.
 *
 * Used whenever there is no photo to apply, or the personalized render could not be
 * produced. Redirecting rather than re-implementing `/file`'s artifact branch is the point:
 * there is exactly ONE implementation of "serve the stored certificate", so the fallback
 * can never drift from it — including the `fileKey`-wins-over-`fileUrl` precedence, the
 * signed-URL redirect and the legacy Firebase streaming path. `/file` re-applies its own
 * gates on arrival, so this hop grants nothing that endpoint would not have granted.
 */
/**
 * The deterministic object key for ONE certificate rendered with ONE specific photo.
 *
 *   events/{eventSlug}/certificates/personalized/{certificateId}__{photoVersion}.pdf
 *
 * THE PHOTO VERSION IS THE WHOLE INVALIDATION STRATEGY. `attendeePhotoKey` is generated by
 * `generateObjectId()` on every upload, so it is unique per photo. Replacing the photo
 * therefore changes this key, the old artifact is simply never addressed again, and the next
 * download renders exactly one new file. No invalidation write, and — importantly — no change
 * to the photo upload/replacement route.
 *
 * IT IS ALSO THE CONCURRENCY STRATEGY. Two simultaneous first downloads derive the SAME key
 * and produce byte-identical content, so the second PutObject is a harmless overwrite. No
 * lock, no claim, no lease.
 *
 * The key is hashed rather than embedding the raw photo key so the path cannot leak the photo
 * object's location, and stays a safe single path segment.
 */
function personalizedArtifactKey(eventSlug: string, certificateId: string, attendeePhotoKey: string): string {
  const photoVersion = createHash('sha256').update(attendeePhotoKey).digest('hex').slice(0, 16)
  return buildObjectKey({
    type:      'event-certificate',
    eventSlug,
    // Its own folder, so nothing that reasons about the canonical certificates folder can
    // mistake a personalised render for the artifact as issued.
    scopeId:   'personalized',
    objectId:  `${certificateId}__${photoVersion}.pdf`,
  })
}

function toStoredArtifact(req: NextRequest, certificateId: string): NextResponse {
  const url = new URL(`/api/certificates/${encodeURIComponent(certificateId)}/file`, req.nextUrl.origin)
  url.search = req.nextUrl.search
  return NextResponse.redirect(url, { status: 302, headers: { 'Cache-Control': 'no-store' } })
}

export async function GET(req: NextRequest, { params }: Params): Promise<NextResponse> {
  // Same per-IP throttle as the stored-PDF endpoint. Rendering costs more than streaming, so
  // this route must never be the cheaper way to ask for the same bytes.
  const rl = checkPolicy(getClientIp(req), RATE_POLICY.pdfDownload)
  if (rl.limited) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again shortly.' },
      { status: 429, headers: { 'Retry-After': String(rl.retryAfter) } },
    )
  }

  const { certificateId } = await params

  if (!isValidCertificateId(certificateId)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const cert = await getCertificate(certificateId)
  // Identical existence rule to `/file`: EITHER artifact makes a certificate downloadable.
  // Kept even though a personalized render does not read the artifact, so this route can
  // never surface a certificate that `/file` would 404 — it is a second door to the same
  // room, not a wider one.
  if (!cert || (!cert.fileUrl && !cert.fileKey)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  // Revoked is always blocked — for organizer and attendee alike.
  if (cert.status === 'revoked') {
    return NextResponse.json({ error: 'This certificate has been revoked' }, { status: 410 })
  }

  // Is this an authenticated request from the owning organizer?
  let isOrganizer = false
  const authHeader = req.headers.get('authorization') ?? ''
  if (authHeader.startsWith('Bearer ')) {
    try {
      const uid = (await adminAuth.verifyIdToken(authHeader.slice(7))).uid
      isOrganizer = uid === cert.organizerUid
    } catch { /* ignore — treat as public */ }
  }

  // Attendee-facing gating (organizer bypasses) — the same three settings, read from the
  // same document, with the same defaults as `/file`.
  if (!isOrganizer) {
    const download = (await getSettings(cert.eventId))?.download ?? defaultCertificateSettings().download

    if (!download.enabled) {
      return NextResponse.json({ error: 'Downloads are disabled for this certificate.' }, { status: 403 })
    }
    if (!download.allowAttendee) {
      return NextResponse.json({ error: 'Downloads are restricted by the organizer.' }, { status: 403 })
    }
    if (download.requireVerification) {
      const token = req.nextUrl.searchParams.get('token') ?? ''

      // The shapes are disjoint (capability = "<expiry>.<64 hex>", permanent = bare 64 hex),
      // so exactly one comparison runs — a capability can never be tried against, or
      // substituted for, the permanent token.
      const viaCapability = looksLikeDownloadCapability(token)
        && verifyCertificateDownloadCapability(cert.certificateId, cert.eventSlug, token)

      const viaPermanent = !!cert.verificationToken && timingSafeEqualStr(token, cert.verificationToken)

      if (!viaCapability && !viaPermanent) {
        return NextResponse.json({ error: 'Verification required to download this certificate.' }, { status: 403 })
      }
    }
  }

  // ═══ NOTHING TO PERSONALIZE ═════════════════════════════════════════════════
  // No photo on this certificate — the attendee still gets their certificate. This is the
  // path a stale client takes (it believed a photo existed, or the photo was removed after
  // the page loaded), so it must be ordinary, not an error.
  if (!cert.attendeePhotoKey) return toStoredArtifact(req, certificateId)

  // The key comes from the certificate record loaded above — NEVER from the request. A
  // caller cannot name the bytes that get embedded, only the certificate they have already
  // proved they may download.
  const artifactKey = personalizedArtifactKey(cert.eventSlug, certificateId, cert.attendeePhotoKey)

  // ── Already rendered for THIS photo? Serve it without touching pdf-lib. ────
  // `exists` distinguishes NOT_FOUND from a credential/bucket fault: it returns false only
  // for a genuinely absent object and THROWS otherwise. Treating a storage fault as "absent"
  // would silently turn every request back into a render — the exact cost this removes — so a
  // throw falls through to the render path deliberately, and only for that one request.
  let cached = false
  try {
    cached = await storage.exists(artifactKey)
  } catch (err) {
    captureError(err, { scope: 'certificate_personalized_cache_probe', area: 'certificate', certificateId })
  }

  if (!cached) {
    // The key comes from the certificate record loaded above — NEVER from the request. A
    // caller cannot name the bytes that get embedded, only the certificate they have already
    // proved they may download.
    const rendered = await renderCertificateOnDemand(certificateId, {
      attendeePhotoKeyOverride: cert.attendeePhotoKey,
    })

    if (!rendered.ok) {
      // A missing/stripped template or a render failure must not deny the attendee the
      // certificate they are entitled to — degrade to the stored artifact, which is exactly
      // what they would have received before this route existed.
      captureError(new Error(`personalized_render_failed:${rendered.error}`), {
        scope: 'certificate_personalized_download', area: 'certificate', certificateId,
      })
      return toStoredArtifact(req, certificateId)
    }

    try {
      // Same asset type, visibility and size policy as the canonical artifact — only the key
      // differs. `assertVisibilityAllowed` still refuses a PUBLIC certificate outright.
      await storage.upload({
        type:       'event-certificate',
        eventSlug:  cert.eventSlug,
        scopeId:    'personalized',
        id:         artifactKey.slice(artifactKey.lastIndexOf('/') + 1),
        body:       rendered.bytes,
        mimeType:   'application/pdf',
        visibility: 'SIGNED_URL',
        uploadedBy: `certificate:${certificateId}`,
      })
    } catch (err) {
      // Persisting is an OPTIMISATION. If storage refuses, the attendee still gets their
      // certificate this time; the next request simply renders again.
      captureError(err, { scope: 'certificate_personalized_persist', area: 'certificate', certificateId })
      void incrementCertificateDownload(certificateId).catch(() => {})
      return new NextResponse(Buffer.from(rendered.bytes), {
        status: 200,
        headers: {
          'Content-Type':        'application/pdf',
          'Content-Disposition': `inline; filename="${rendered.filename}"`,
          'Cache-Control':       'no-store',
        },
      })
    }
  }

  // Best-effort tracking — never block the download on a counter write. Counted here because
  // this route does not pass through `/file`.
  void incrementCertificateDownload(certificateId).catch(() => {})

  // Served through the ORDINARY signed-URL mechanism, exactly like the canonical artifact:
  // the bytes come from R2, not from this function. `inline` preserves the previous viewing
  // behaviour (the canonical route uses `attachment`).
  //
  // `no-store` applies to THIS REDIRECT, not to the artifact. The signed URL expires, so the
  // 302 must never be cached — reuse comes from the persisted object, which is why repeat
  // downloads no longer render.
  const url = await storage.generateSignedUrl({
    path:      artifactKey,
    operation: 'read',
    expiresIn: ARTIFACT_SIGNED_URL_TTL_S,
    // certificateId passed isValidCertificateId above, so no quote or CRLF can reach here.
    responseContentDisposition: `inline; filename="certificate-${certificateId}.pdf"`,
  })

  return NextResponse.redirect(url, { status: 302, headers: { 'Cache-Control': 'no-store' } })
}
