// RD-RACEOPS-01 Sprint 2 · Result import — every tunable, in ONE place.
//
// "No hardcoded values": nothing below may be repeated inline anywhere in the module.
//
// Why results get their own caps rather than reusing IMPORT_MAX_ROWS (2,000) /
// IMPORT_MAX_FILE_BYTES (5 MB) from lib/registrations/importTemplate.ts: those bound a
// MANUAL participant-entry template, where 2,000 is a sane human limit. A results file
// is machine-generated by a timing provider — a large city marathon legitimately
// exceeds 20,000 finishers in one race. Reusing the registration caps would reject
// valid files. These constants are deliberately separate and separately justified.

/** Upper bound on data rows in one results file. */
export const RESULTS_MAX_ROWS = 50_000

/** Upper bound on uploaded file size. */
export const RESULTS_MAX_FILE_BYTES = 15 * 1024 * 1024   // 15 MB

/** Extensions accepted in Sprint 2. PDF and ZIP are explicitly future-only. */
export const RESULTS_ACCEPTED_EXTENSIONS = ['.csv', '.xlsx'] as const

/** `accept` attribute for the file input — derived, never written out by hand. */
export const RESULTS_FILE_ACCEPT = RESULTS_ACCEPTED_EXTENSIONS.join(',')

/** Rows rendered in the preview table before paging. The full validated set stays in
 *  memory; this only bounds what is painted, so a 50k-row file cannot stall the tab. */
export const RESULTS_PREVIEW_PAGE_SIZE = 50

/** Rows shown in the on-screen issue list. The downloadable CSV report is never
 *  truncated — see buildValidationReportCsv. */
export const RESULTS_ISSUE_PREVIEW_LIMIT = 200

/** Filename stem for the downloadable validation report. */
export const VALIDATION_REPORT_FILENAME_STEM = 'validation-report'

export function formatMaxFileSize(): string {
  return `${Math.round(RESULTS_MAX_FILE_BYTES / (1024 * 1024))} MB`
}
