// GET /api/receipts/[registrationId]
//
// Returns a downloadable payment receipt PDF.
// Only available for paid registrations (amount > 0, paymentStatus !== 'not_required').
//
// Authorization (checked in order):
//   1. ?token=<hmac>   — HMAC-SHA256(TICKET_SECRET, "receipt:<id>") signed link.
//                        Generated by signReceiptToken().  Used in confirmation emails.
//   2. Authorization: Bearer <firebase-id-token>
//      — registration owner (reg.uid === uid) OR
//      — event organizer   (reg.organizerUid === uid)

import { NextRequest, NextResponse }  from 'next/server'
import { adminDb, adminAuth }          from '@/lib/firebase/admin'
import { getClientIp }                 from '@/lib/rateLimit'
import { RATE_POLICY, checkPolicy }    from '@/lib/rateLimit/policies'
import { verifyReceiptToken }          from '@/lib/receipts/token'
import { generateReceiptPdf }          from '@/lib/receipts/pdf'
import type { RegistrationDocument }   from '@/lib/registrations/types'
import type { PaymentIntentRecord }    from '@/lib/firebase/firestore/paymentIntents'

function toIso(val: unknown): string | null {
  if (!val) return null
  if (typeof val === 'object' && 'toDate' in (val as object)) {
    return (val as { toDate: () => Date }).toDate().toISOString()
  }
  return null
}

function fmtTransactionDate(iso: string | null): string {
  if (!iso) return 'N/A'
  return new Date(iso).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

export async function GET(
  req:     NextRequest,
  context: { params: Promise<{ registrationId: string }> },
): Promise<NextResponse> {
  const { registrationId } = await context.params

  // Throttle on-the-fly PDF generation per client IP (CPU-exhaustion guard).
  const rl = checkPolicy(getClientIp(req), RATE_POLICY.pdfDownload)
  if (rl.limited) return NextResponse.json(
    { error: 'Too many requests. Please try again later.' },
    { status: 429, headers: { 'Retry-After': String(rl.retryAfter) } },
  )

  // ── Load registration ──────────────────────────────────────────────────────
  const regSnap = await adminDb.collection('registrations').doc(registrationId).get()
  if (!regSnap.exists) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }
  const reg = regSnap.data() as RegistrationDocument

  // ── Guard: only paid registrations have receipts ───────────────────────────
  if (reg.amount === 0 || reg.paymentStatus === 'not_required') {
    return NextResponse.json(
      { error: 'No receipt available for free registrations' },
      { status: 404 },
    )
  }

  // ── Authorization ──────────────────────────────────────────────────────────
  const tokenParam = req.nextUrl.searchParams.get('token') ?? ''
  if (tokenParam) {
    if (!verifyReceiptToken(registrationId, tokenParam)) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
  } else {
    const bearerToken = (req.headers.get('authorization') ?? '').replace(/^Bearer /, '')
    let authed = false
    if (bearerToken) {
      try {
        const decoded = await adminAuth.verifyIdToken(bearerToken)
        const uid = decoded.uid
        authed = (reg.uid === uid) || (reg.organizerUid === uid)
      } catch { /* invalid token */ }
    }
    if (!authed) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
  }

  // ── Load payment intent for paymentId and transaction date ─────────────────
  let paymentId       = 'N/A'
  let transactionDate = 'N/A'

  const piSnap = await adminDb
    .collection('paymentIntents')
    .where('registrationId', '==', registrationId)
    .limit(1)
    .get()

  if (!piSnap.empty) {
    const pi = piSnap.docs[0].data() as PaymentIntentRecord
    paymentId = pi.paymentId ?? 'N/A'
    const piIso = toIso(pi.updatedAt)
    transactionDate = fmtTransactionDate(piIso)
  }

  // ── Load event for organizer name ──────────────────────────────────────────
  let organizerName = 'Event Organiser'
  const eventSnap   = await adminDb.collection('events').doc(reg.eventSlug).get()
  if (eventSnap.exists) {
    const event = eventSnap.data() as Record<string, unknown>
    const ed    = event.eventDetails as Record<string, unknown> | null
    const org   = ed?.organizer as Record<string, unknown> | null
    if (typeof org?.name === 'string' && org.name.trim()) {
      organizerName = org.name.trim()
    }
  }

  // ── Generate PDF ───────────────────────────────────────────────────────────
  const pdfBytes = await generateReceiptPdf({
    registrationId:  registrationId,
    ticketCode:      reg.ticketCode,
    attendeeName:    reg.attendee.name,
    attendeeEmail:   reg.attendee.email,
    passName:        reg.passName,
    eventName:       reg.eventName,
    organizerName,
    amountPaid:      reg.amount,
    paymentId,
    transactionDate,
  })

  return new NextResponse(Buffer.from(pdfBytes), {
    status:  200,
    headers: {
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="receipt-${reg.ticketCode}.pdf"`,
      'Cache-Control':       'no-store',
    },
  })
}
