// GET /api/tickets/[registrationId]/pdf
//
// Generates a downloadable PDF ticket on-the-fly.
//
// Authorization (checked in order):
//   1. ?token=<hmac>  — HMAC-SHA256(TICKET_SECRET, registrationId) signed link.
//                       Generated server-side by the ticket page and email flows.
//   2. Authorization: Bearer <firebase-id-token>  — authenticated as the
//      registration owner (reg.uid === uid) or the event organizer
//      (reg.organizerUid === uid).
//
// When TICKET_SECRET is not configured, a server warning is logged and the
// route falls back to the old UUID-as-capability-token behaviour so existing
// links keep working.  Set TICKET_SECRET in production to enable full auth.
//
// QR code is rendered as filled rectangles from the qrcode matrix so no canvas
// native module is needed.

import { NextRequest, NextResponse }   from 'next/server'
import { adminDb, adminAuth }           from '@/lib/firebase/admin'
import { getClientIp }                  from '@/lib/rateLimit'
import { RATE_POLICY, checkPolicy }     from '@/lib/rateLimit/policies'
import { getEventBySlug }               from '@/lib/firebase/firestore/events'
import { buildQrValue, verifyTicketToken } from '@/lib/tickets/generate'
import { generateTicketPdf } from '@/lib/tickets/pdf'
import type { RegistrationDocument }    from '@/lib/registrations/types'
import type { EventDetailsDraft }       from '@/components/wizard/eventDetailsConfig'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(dateStr: string): string {
  if (!dateStr) return ''
  const [y, m, d] = dateStr.split('-').map(Number)
  return new Date(y, m - 1, d).toLocaleDateString('en-IN', {
    weekday: 'short', day: 'numeric', month: 'long', year: 'numeric',
  })
}

function toIso(val: unknown): string | null {
  if (!val) return null
  if (typeof val === 'object' && 'toDate' in (val as object)) {
    return (val as { toDate: () => Date }).toDate().toISOString()
  }
  return null
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export async function GET(
  req:    NextRequest,
  context: { params: Promise<{ registrationId: string }> },
): Promise<NextResponse> {
  const { registrationId } = await context.params

  // Throttle on-the-fly PDF generation per client IP (CPU-exhaustion guard).
  const rl = checkPolicy(getClientIp(req), RATE_POLICY.pdfDownload)
  if (rl.limited) return NextResponse.json(
    { error: 'Too many requests. Please try again later.' },
    { status: 429, headers: { 'Retry-After': String(rl.retryAfter) } },
  )

  // ── Load registration ─────────────────────────────────────────────────────
  const regSnap = await adminDb.collection('registrations').doc(registrationId).get()
  if (!regSnap.exists) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }
  const reg = regSnap.data() as RegistrationDocument

  // ── Authorization ─────────────────────────────────────────────────────────
  // Path 1: HMAC-signed token in query string (generated by signTicketToken).
  // Path 2: Firebase ID token — registration owner (reg.uid) or organizer.
  // Both paths require valid credentials; there is no unauthenticated fallback.
  const tokenParam = req.nextUrl.searchParams.get('token') ?? ''
  if (tokenParam) {
    if (!verifyTicketToken(registrationId, tokenParam)) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
    // Token verified — proceed
  } else {
    // Path 2: Firebase ID token (registration owner or organizer)
    const bearerToken = (req.headers.get('authorization') ?? '').replace(/^Bearer /, '')
    let authed = false

    if (bearerToken) {
      try {
        const decoded = await adminAuth.verifyIdToken(bearerToken)
        const uid = decoded.uid
        authed = (reg.uid === uid) || (reg.organizerUid === uid)
      } catch {
        // Invalid token — fall through to 403
      }
    }

    if (!authed) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
  }

  const qrValue = reg.ticket?.qrValue ?? buildQrValue(reg.eventSlug, registrationId, reg.ticketCode)

  // ── Load event ────────────────────────────────────────────────────────────
  const event    = await getEventBySlug(reg.eventSlug)
  const ed       = event?.eventDetails as EventDetailsDraft | undefined
  const startDate = ed?.schedule?.startDate ?? ''
  const startTime = ed?.schedule?.startTime ?? ''
  const venueType = ed?.venue?.type
  const venueName = venueType === 'online'
    ? (ed?.venue?.online?.platform ?? 'Online')
    : (ed?.venue?.physical?.name ?? '')
  const venueCity = venueType !== 'online' ? (ed?.venue?.physical?.city ?? '') : ''

  // Venue as one display string; the generator wraps it against real font metrics.
  const venueLabel = [venueName, venueCity].filter(Boolean).join(', ')

  const registeredAt = toIso(reg.registeredAt)

  // ── Build PDF ─────────────────────────────────────────────────────────────
  // RD-TICKET-REDESIGN: the layout moved to lib/tickets/pdf.ts, mirroring how the receipt
  // PDF is organised. Same library, same sanitising discipline — not a second PDF system.
  // The route keeps what only the route can do: authorization, the bounded reads, and the
  // QR payload below, which is passed through byte-identical so check-in is unaffected.
  const pdfBytes = await generateTicketPdf({
    qrValue,
    ticketCode:     reg.ticketCode,
    registrationId,
    attendeeName:   reg.attendee.name,
    passName:       reg.passName,
    eventName:      reg.eventName,
    ...(startDate ? { eventDate: fmt(startDate) } : {}),
    ...(startTime ? { eventTime: startTime } : {}),
    ...(venueLabel ? { venue: venueLabel } : {}),
    ...(registeredAt ? { registeredOn: new Date(registeredAt).toLocaleDateString('en-IN', {
      day: 'numeric', month: 'short', year: 'numeric',
    }) } : {}),
    status:         reg.status,
  })

  return new NextResponse(Buffer.from(pdfBytes), {
    status: 200,
    headers: {
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="ticket-${reg.ticketCode}.pdf"`,
      'Cache-Control':       'no-store',
    },
  })
}
