'use client'

// RD-BADGE-01 · Participant badge card — download + share.
//
// The ONE client component on the public runner page. Everything else there stays a server
// component.
//
// No social SDK is integrated. Sharing is a download, a copyable link, the Web Share API
// where the browser offers it, and — RD-RESULTS-PUBLIC-FIX-01 — three plain intent URLs for
// desktop, where no native share sheet exists. None of them loads third-party script.

import { useCallback, useState } from 'react'
import { Award, Check, Copy, Download, Share2 } from 'lucide-react'
import { Button } from '@/components/ui'
import { cn } from '@/lib/utils/cn'

export interface BadgeShareProps {
  /** Public image endpoint for this result. */
  badgeUrl:  string
  /** Stable page URL a participant copies and shares. */
  shareUrl:  string
  runnerName: string
  raceName:   string
}

/**
 * One share destination.
 *
 * A link, not a button: it navigates, and a screen reader should announce it as such.
 * `noreferrer` as well as `noopener` — the destination has no need to know where the
 * visitor came from.
 */
function ShareChannel({ label, href }: { label: string; href: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex h-11 items-center gap-2 rounded-lg border border-border px-4 text-fs-sm font-medium text-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
    >
      <Share2 className="size-4" aria-hidden />
      {label}
    </a>
  )
}

export function BadgeShare({ badgeUrl, shareUrl, runnerName, raceName }: BadgeShareProps) {
  const [copied, setCopied] = useState(false)
  const [failed, setFailed] = useState(false)

  const copyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setFailed(false)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard access is refused in some browsers/contexts. Say so rather than appearing
      // to have copied nothing.
      setFailed(true)
    }
  }, [shareUrl])

  const nativeShare = useCallback(async () => {
    if (!navigator.share) return
    try {
      await navigator.share({
        title: `${runnerName} — ${raceName}`,
        text:  `My ${raceName} result`,
        url:   shareUrl,
      })
    } catch {
      // The user dismissed the sheet, or the browser refused. Neither is an error worth
      // surfacing.
    }
  }, [runnerName, raceName, shareUrl])

  const canNativeShare = typeof navigator !== 'undefined' && typeof navigator.share === 'function'

  return (
    <section aria-label="Finisher badge" className="mb-6">
      <div className="overflow-hidden rounded-2xl border border-border bg-card">
        {/* The badge itself. A plain <img>: the image is generated by our own API route, and
            next/image would add a second optimisation pass over an already-optimised PNG. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={badgeUrl}
          alt={`Finisher badge for ${runnerName} — ${raceName}`}
          width={1080}
          height={1080}
          loading="lazy"
          className="block aspect-square w-full bg-muted object-cover"
        />

        <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="min-w-0">
            <h2 className="flex items-center gap-2 text-fs-md font-semibold text-foreground">
              <Award className="size-4 shrink-0 text-primary" aria-hidden />
              Your finisher badge
            </h2>
            <p className="mt-1 text-fs-sm leading-relaxed text-muted-foreground">
              Download it, or copy the link to share your result.
            </p>
          </div>

          <div className="flex shrink-0 flex-wrap gap-2">
            <a
              href={`${badgeUrl}?download=1`}
              download
              className={cn(
                'inline-flex h-11 items-center justify-center gap-2 rounded-xl px-5',
                'text-fs-base font-semibold text-primary-foreground',
                'transition-opacity hover:opacity-90',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2',
              )}
              style={{ backgroundImage: 'var(--primary-gradient)' }}
            >
              <Download className="size-4" aria-hidden />
              Download
            </a>

            <Button variant="outline" size="sm" className="h-11" onClick={() => void copyLink()}>
              {copied
                ? <><Check className="size-4 text-success" aria-hidden /> Copied</>
                : <><Copy className="size-4" aria-hidden /> Copy link</>}
            </Button>

            {canNativeShare && (
              <Button variant="outline" size="sm" className="h-11" onClick={() => void nativeShare()}>
                <Share2 className="size-4" aria-hidden />
                Share
              </Button>
            )}

            {/* ═══ RD-RESULTS-PUBLIC-FIX-01 · named channels ══════════════════
                The native sheet above covers these on a phone, and does not exist on most
                desktop browsers — where sharing a result is exactly what someone wants to do.
                Plain intent URLs: no SDK, no tracking pixel, no third-party script, and
                nothing to consent to. Each opens in a new tab with noopener/noreferrer.

                They share the RESULT PAGE, never the badge image URL — the page carries the
                OpenGraph card, so the preview is generated by the receiving platform from
                metadata this product already emits. */}
            <ShareChannel
              label="WhatsApp"
              href={`https://wa.me/?text=${encodeURIComponent(`${runnerName} — ${raceName} result: ${shareUrl}`)}`}
            />
            <ShareChannel
              label="Facebook"
              href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`}
            />
            <ShareChannel
              label="LinkedIn"
              href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`}
            />
          </div>
        </div>

        {failed && (
          <p role="alert" className="border-t border-border px-5 py-3 text-fs-sm text-muted-foreground">
            Your browser blocked clipboard access. The link is{' '}
            <span className="break-all font-mono text-fs-2xs">{shareUrl}</span>
          </p>
        )}
      </div>
    </section>
  )
}
