// POST /api/registrations/create-order
//
// Security model:
//   1. Firebase ID token in Authorization header (optional — guest checkout supported).
//   2. Event and pass loaded from Firestore — never trust client-supplied price.
//   3. All registration-rule checks (requireLogin, limitPerEmail, limitPerMobile)
//      run server-side before creating the order, so the user never pays and gets blocked.
//   4. Gate check runs server-side.
//   5. Payment intent written to Firestore (with authoritative amount) before returning.

import { NextRequest, NextResponse } from 'next/server'
import { adminAuth }                 from '@/lib/firebase/admin'
import { checkDuplicateRegistration } from '@/lib/registrations/duplicateCheck'
import { captureFinancialError }     from '@/lib/monitoring/sentry'
import { checkRegistrationGate }     from '@/lib/registrations/gate'
import { getEventBySlug }            from '@/lib/firebase/firestore/events'
import {
  createPaymentIntent, getPaymentIntent, getAttemptClaim, claimPaymentAttempt,
} from '@/lib/firebase/firestore/paymentIntents'
// RD-PAY-P0-2 — one registration attempt, one active order.
import {
  decideExistingIntent, normalizeIdempotencyKey, attemptClaimId,
} from '@/lib/registrations/paymentAttempt'
import { razorpay, RAZORPAY_KEY_ID } from '@/lib/razorpay/client'   // C1: throws if keys absent
import { getClientIp } from '@/lib/rateLimit'
import { checkDistributedRateLimit } from '@/lib/rateLimit/redis'
import { validateCoupon }            from '@/lib/coupons/validate'
import { resolveEffectivePassPricePaise } from '@/lib/pricing/earlyBird'
import { resolveAttendeeIdentity }   from '@/lib/registrations/attendeeIdentity'
import type { IdentityField }        from '@/lib/registrations/attendeeIdentity'
import { validateInviteCode }        from '@/app/api/registrations/validate-invite-code/route'
import { validateFormResponses, sanitizeFormResponses } from '@/lib/registrations/validateFormResponses'
import { resolveServerEligibility }  from '@/lib/registrations/ageEligibility'
import type { RegistrationRules } from '@/components/wizard/registrationFormConfig'
// RD-PAYMENT-02 Phase 4 — feature-gated canonical charge amount.
import { resolvePlatformPricing }    from '@/lib/platform/pricing/resolver'
import { resolveCheckoutCharge }     from '@/lib/fees/checkoutCharge'
import { resolveFeeConfig }          from '@/lib/fees/resolveFeeConfig'
import { getFeePlanForOrganizer }    from '@/lib/billing/feeEngine'
import { builderFeeModelToEngine, normalizeFeeModel } from '@/lib/events/builder/types'
import type { FeeConfig, FeeBreakdownRecord } from '@/lib/fees/types'

// ─── Request / response shapes ────────────────────────────────────────────────

interface CreateOrderBody {
  slug:    string
  passId:  string
  attendee: {
    name:   string
    email:  string
    phone?: string
  }
  formResponses: Record<string, string>
  couponCode?:   string
  inviteCode?:   string
  // RD-PAY-P0-2 — per-attempt key generated by the client (and regenerated when the pass
  // changes). Previously sent and IGNORED, which is why every retry minted a second order.
  idempotencyKey?: string
}

export interface CreateOrderResponse {
  orderId:       string
  amount:        number    // paise (already reflects any coupon discount)
  currency:      string
  keyId:         string    // Razorpay key_id for client-side checkout
  // When a coupon reduces the total to zero, no Razorpay order is created.
  // The client should call /api/registrations/submit with this couponCode instead.
  isCouponFree?: boolean
  couponCode?:   string
  // RD-PAY-P0-2 — true when this is the SAME order a previous call already minted for this
  // attempt. The client shows checkout for it exactly as it would a new one; the flag exists
  // so the difference is observable in logs and tests.
  reused?:       boolean
  // RD-PAY-P0-2 — this attempt already produced a confirmed registration. The client must
  // send the attendee to their ticket, NOT to Razorpay.
  alreadyRegistered?: boolean
  registrationId?:    string
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())
}

/** Firestore Timestamp | Date | epoch-ms → epoch ms. Null when unreadable. */
function toMillis(v: unknown): number | null {
  if (typeof v === 'number') return v
  if (v instanceof Date) return v.getTime()
  const t = v as { toMillis?: () => number; toDate?: () => Date } | null
  if (t && typeof t.toMillis === 'function') return t.toMillis()
  if (t && typeof t.toDate === 'function') return t.toDate().getTime()
  return null
}

/**
 * RD-PAY-P0-2 — is there money on this order already?
 *
 * Mirrors `findCapturedLicensePayment` in app/api/licensing/purchase/route.ts. Returns the
 * payment id when Razorpay holds a captured OR authorized payment for the expected amount.
 *
 * `authorized` counts: the funds are held and can still be captured (by the dashboard, by
 * auto-capture, or by the webhook), so replacing the order would strand a real payment.
 *
 * FAIL-CLOSED. If Razorpay cannot be reached we return a sentinel rather than null, because
 * "we could not ask" must never be read as "there is no payment" — that is exactly the
 * inference that produces a double charge.
 */
async function findCapturedRegistrationPayment(
  orderId: string,
  expectedAmountPaise: number,
): Promise<string | null> {
  if (expectedAmountPaise <= 0) return null
  try {
    const res = await razorpay.orders.fetchPayments(orderId) as {
      items?: Array<{ id?: string; status?: string; amount?: number; currency?: string }>
    }
    const hit = (res.items ?? []).find(p =>
      (p.status === 'captured' || p.status === 'authorized') &&
      p.currency === 'INR' && p.amount === expectedAmountPaise)
    return hit?.id ?? null
  } catch (err) {
    captureFinancialError(err, { scope: 'create-order.fetch_payments_failed', detail: 'treated as CAPTURED (fail-closed)', orderId })
    return 'unknown'
  }
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export async function POST(
  req: NextRequest,
): Promise<NextResponse<CreateOrderResponse | { error: string; reason?: string }>> {
  // ── 0. Rate limit: 10 order attempts per 10 minutes per IP (distributed) ──
  const ip = getClientIp(req)
  const rl = await checkDistributedRateLimit({ key: `create-order:${ip}`, limit: 10, windowSeconds: 10 * 60, failOpen: true })
  if (!rl.allowed) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again later.' },
      {
        status: 429,
        headers: {
          'Retry-After':       String(Math.ceil((rl.resetAt - Date.now()) / 1000)),
          'X-RateLimit-Limit': '10',
          'X-RateLimit-Reset': String(rl.resetAt),
        },
      },
    )
  }

  // ── 1. Optional auth ───────────────────────────────────────────────────────
  let uid: string | undefined
  const authHeader = req.headers.get('authorization') ?? ''
  const token      = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : ''
  if (token) {
    try {
      const decoded = await adminAuth.verifyIdToken(token)
      uid = decoded.uid
    } catch { /* fall through as guest */ }
  }

  // ── 2. Parse body ──────────────────────────────────────────────────────────
  let body: CreateOrderBody
  try {
    body = (await req.json()) as CreateOrderBody
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
  }

  const { slug, passId, formResponses, couponCode, inviteCode } = body
  // Malformed / absent → null, and the route behaves exactly as it did before this
  // feature: a fresh order every time. Never an error — an attendee must not be blocked
  // from paying because their browser produced an unusable key.
  const idempotencyKey = normalizeIdempotencyKey(body.idempotencyKey)

  if (!slug || !passId || !body.attendee?.name?.trim() || !body.attendee?.email?.trim()) {
    return NextResponse.json(
      { error: 'slug, passId, attendee.name and attendee.email are required' },
      { status: 400 },
    )
  }
  if (!isValidEmail(body.attendee.email)) {
    return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
  }

  // ── 3. Gate check (server-side) ────────────────────────────────────────────
  const gate = await checkRegistrationGate(slug, passId)
  if (!gate.allowed) {
    return NextResponse.json(
      { error: 'Registration is not available', reason: gate.reason },
      { status: 403 },
    )
  }

  // ── 4. Load event and pass (Firestore is source of truth) ─────────────────
  const event = await getEventBySlug(slug)
  if (!event) return NextResponse.json({ error: 'Event not found' }, { status: 404 })

  const rawPricing = event.pricing as Record<string, unknown> | null
  const passes     = Array.isArray(rawPricing?.passes)
    ? (rawPricing!.passes as Record<string, unknown>[])
    : []
  const pass = passes.find(p => p.id === passId)
  if (!pass) return NextResponse.json({ error: 'Pass not found' }, { status: 404 })

  // Server-authoritative base amount (integer paise): the early-bird price while active
  // (before its cutoff), otherwise the regular price. Resolved from the stored pass only
  // via the ONE canonical resolver — the client amount is never trusted. Backward-
  // compatible: passes without early bird resolve to Math.round(price*100) unchanged.
  const originalAmountPaise = resolveEffectivePassPricePaise(pass, Date.now())
  if (originalAmountPaise === 0) {
    return NextResponse.json(
      { error: 'This pass is free. Use /api/registrations/submit instead.' },
      { status: 400 },
    )
  }

  const passName     = typeof pass.name     === 'string' ? pass.name     : 'Pass'
  const passCapacity = pass.unlimited === true
    ? null
    : typeof pass.quantity === 'number' ? pass.quantity : null

  // ── 5. Enforce registration rules before charging the user ─────────────────
  const registrationForm = event.registrationForm
  const regRules         = registrationForm?.registrationRules as RegistrationRules | undefined

  if (regRules?.requireLogin && !uid) {
    return NextResponse.json(
      { error: 'You must be signed in to register for this event.', reason: 'LOGIN_REQUIRED' },
      { status: 401 },
    )
  }

  // Canonical attendee identity (RD-ATTENDEE-03A C1): derive the authoritative stored
  // identity from the submitted responses via the ONE shared resolver (the same the
  // client used), falling back to the client-sent values. Dedup + payment-intent +
  // ticket all read this single model.
  // RD-RT4.0 — strip anything that is not a configured field before it is validated,
  // used for identity, or stored on the payment intent.
  const safeResponses  = sanitizeFormResponses(registrationForm?.sections ?? [], formResponses)
  const identityFields = ((registrationForm?.sections ?? []) as { fields: IdentityField[] }[]).flatMap(s => s.fields)
  const identity = resolveAttendeeIdentity(identityFields, safeResponses)
  const attendee = {
    name:  (identity.name  || body.attendee.name).trim(),
    email: (identity.email || body.attendee.email).trim().toLowerCase(),
    phone: (identity.phone || body.attendee.phone || '').trim() || undefined,
  }

  const normEmail = attendee.email.trim().toLowerCase()

  // P0-4: Phone required when limitPerMobile is active. Without this guard an
  // attendee who omits their phone bypasses the uniqueness rule entirely. Mirrors
  // the enforcement already present in submit/route.ts.
  if (regRules?.limitPerMobile && !attendee.phone?.trim()) {
    return NextResponse.json(
      { error: 'A phone number is required to register for this event.', reason: 'PHONE_REQUIRED' },
      { status: 400 },
    )
  }

  // H2: authoritative duplicate check via the ONE shared helper (also used by the
  // pre-payment pre-check and submit) — never charge a user for a duplicate.
  const dup = await checkDuplicateRegistration({
    slug,
    email:          attendee.email,
    phone:          attendee.phone,
    limitPerEmail:  regRules?.limitPerEmail  ?? false,
    limitPerMobile: regRules?.limitPerMobile ?? false,
  })
  if (dup.duplicate) {
    return dup.field === 'mobile'
      ? NextResponse.json({ error: 'A registration with this mobile number already exists.', reason: 'DUPLICATE_MOBILE' }, { status: 409 })
      : NextResponse.json({ error: 'A registration with this email address already exists.', reason: 'DUPLICATE_EMAIL' }, { status: 409 })
  }

  // ── 5c. Invite code validation (P0-1) ─────────────────────────────────────
  // submit/route.ts validates invite codes for free registrations; this mirrors
  // that check for paid registrations so the paid flow cannot bypass invite-only
  // access control by calling the API directly.
  const inviteCheck = validateInviteCode(event.accessControl, inviteCode?.trim() ?? '')
  if (!inviteCheck.valid) {
    return NextResponse.json(
      { error: inviteCheck.error ?? 'Invalid invite code.', reason: 'INVITE_CODE_INVALID' },
      { status: 403 },
    )
  }

  // ── 6. Form validation ─────────────────────────────────────────────────────
  // Full validation (conditional + required + per-type formats + configured
  // rules) — the same rules the builder/client enforce — before charging.
  if (registrationForm?.sections?.length) {
    // RD-RT4.0 — age eligibility enforced before any charge is created, from the
    // server-loaded pass + event date, through the same shared rule the client uses.
    const eligibility = resolveServerEligibility(event.eventDetails as Record<string, unknown>, pass)
    const validationError = validateFormResponses(registrationForm, passId, safeResponses, eligibility)
    if (validationError) {
      return NextResponse.json(
        { error: validationError.message },
        { status: 400 },
      )
    }
  }

  // ── 7. Resolve event name ──────────────────────────────────────────────────
  const rawDetails = event.eventDetails as Record<string, unknown>
  const rawInfo    = rawDetails?.info as Record<string, unknown> | null
  const eventName  = typeof rawInfo?.name === 'string' ? rawInfo.name : 'Event'

  // ── 7.5. Validate and apply coupon (server-side — never trust client price) ─
  // originalAmountPaise resolved above (canonical early-bird base).
  let   finalAmountPaise    = originalAmountPaise
  let   couponDocId: string | undefined
  let   discountAmount: number | undefined
  let   appliedCouponCode: string | undefined

  if (couponCode?.trim()) {
    const couponResult = await validateCoupon(slug, couponCode, passId, originalAmountPaise)
    if (!couponResult.valid) {
      return NextResponse.json(
        { error: couponResult.error ?? 'Invalid coupon code.' },
        { status: 400 },
      )
    }
    finalAmountPaise  = couponResult.finalPaise!
    discountAmount    = couponResult.discountPaise!
    couponDocId       = couponResult.couponDocId
    appliedCouponCode = couponResult.coupon!.code

    // Coupon makes the pass free — tell the client to use the submit (free) flow
    if (finalAmountPaise === 0) {
      return NextResponse.json({
        orderId:      '',
        amount:       0,
        currency:     'INR',
        keyId:        '',
        isCouponFree: true,
        couponCode:   appliedCouponCode,
      })
    }
  }

  // ── 7.6. RD-PAYMENT-02 Phase 4: canonical charge amount (feature-gated) ─────
  // pricingEngineEnabled is the ONLY activation switch. resolvePlatformPricing never
  // throws (falls back to defaults, flag = false), so reading it can't break checkout.
  // When OFF: no fee-config I/O runs and resolveCheckoutCharge returns finalAmountPaise
  //   unchanged, with no breakdown — byte-identical to production.
  // When ON: organizer_pays charges the ticket (chargeAmountPaise === finalAmountPaise);
  //   customer_pays charges ticket + fees. Every current event maps to organizer_pays
  //   (normalizeFeeModel keeps attendee_pays "Coming Soon"), so activating the flag does
  //   NOT change any charge today — it only starts persisting the additive breakdown.
  const platformSettings = await resolvePlatformPricing()
  let feeConfig: FeeConfig | undefined
  if (platformSettings.features.pricingEngineEnabled) {
    const feePlan = await getFeePlanForOrganizer(event.uid)
    feeConfig = await resolveFeeConfig('event_registration', feePlan.planTier)
  }
  const charge = resolveCheckoutCharge({
    pricingEngineEnabled: platformSettings.features.pricingEngineEnabled,
    finalAmountPaise,
    eventFeeModel: builderFeeModelToEngine(
      normalizeFeeModel(rawPricing?.feeModel, platformSettings.features.pricingEngineEnabled),
    ),
    feeConfig,
    context: { organizerUid: event.uid, eventId: slug },
  })
  const amountPaise: number = charge.amountPaise
  const financials: FeeBreakdownRecord | undefined = charge.financials

  // ── 7.7. RD-PAY-P0-2: reuse this attempt's existing order instead of minting a second ──
  //
  // THE BUG THIS CLOSES. Razorpay's `handler` fires only after the money is taken. If
  // verify-payment then timed out / 429'd / 500'd, the old client surfaced a failure and
  // re-armed Pay — and the next tap landed here and minted a BRAND-NEW Razorpay order,
  // charging the attendee a second time for the same registration.
  //
  // The client already generates one `idempotencyKey` per attempt (regenerated on a pass
  // switch, which really is a different attempt). It was sent and ignored. It is now the
  // address of the attempt, so one attempt can only ever have one active order.
  //
  // A CAPTURED PAYMENT ALWAYS WINS. Whenever the persisted order cannot simply be handed
  // back, Razorpay is asked whether anything was captured against it BEFORE a replacement
  // is minted — the same guard, and the same helper shape, the license checkout has used
  // since RD-LICENSE-COUPON-FIX.
  const claimId = idempotencyKey ? attemptClaimId(slug, idempotencyKey) : null
  // True once we have decided to REPLACE an existing claim (its order is terminal, expired
  // or drifted, and Razorpay has confirmed it holds no money). Only then may the claim be
  // overwritten; a first-ever claim uses create() so a concurrent request cannot be lost.
  let supersedingClaim = false
  if (claimId) {
    const claim = await getAttemptClaim(claimId).catch(() => null)
    if (claim?.orderId) {
      const existing = await getPaymentIntent(claim.orderId).catch(() => null)
      if (existing) {
        const decision = decideExistingIntent(
          {
            status:         existing.status,
            registrationId: existing.registrationId,
            refundId:       existing.refundId,
            refundStatus:   existing.refundStatus,
            amount:         existing.amount,
            passId:         existing.passId,
            attendeeEmail:  existing.attendee.email,
            createdAtMs:    toMillis(existing.createdAt),
          },
          { passId, amountPaise, attendeeEmail: normEmail, nowMs: Date.now() },
        )

        if (decision.kind === 'already_registered') {
          // The attempt is finished. Sending this attendee to Razorpay again would be the
          // double charge in its purest form.
          return NextResponse.json({
            orderId: claim.orderId, amount: existing.amount, currency: 'INR', keyId: RAZORPAY_KEY_ID,
            alreadyRegistered: true, registrationId: decision.registrationId,
          })
        }

        if (decision.kind === 'reuse_order') {
          return NextResponse.json({
            orderId: claim.orderId, amount: existing.amount, currency: 'INR', keyId: RAZORPAY_KEY_ID,
            reused: true,
            ...(existing.financials ? { financials: existing.financials } : {}),
          })
        }

        if (decision.kind === 'supersede') {
          // Do NOT replace an order that may already hold the attendee's money.
          const captured = await findCapturedRegistrationPayment(claim.orderId, existing.amount)
          if (captured) {
            captureFinancialError('captured_payment_blocks_new_order', {
              scope: 'create-order.captured_blocks_supersede',
              orderId: claim.orderId, paymentId: captured, eventSlug: slug, passId, why: decision.why,
            })
            return NextResponse.json(
              {
                error: 'We are still confirming your previous payment. Please do not pay again — refresh in a moment and your registration will be completed automatically.',
                reason: 'PAYMENT_IN_PROGRESS',
                orderId: claim.orderId,
              },
              { status: 409 },
            )
          }
        }
        // 'new_order' (terminal: already refunded) and a 'supersede' cleared by the
        // captured-payment check both fall through to mint a replacement — and both must
        // overwrite this attempt's existing claim rather than lose to it.
        supersedingClaim = true
      }
    }
  }

  // ── 8. Create Razorpay order (never trust client amount) ───────────────────
  const receipt     = `rd_${Date.now()}`   // max 40 chars

  let orderId: string
  try {
    const order = await razorpay.orders.create({
      amount:   amountPaise,
      currency: 'INR',
      receipt,
    })
    orderId = order.id
  } catch (err) {
    captureFinancialError(err, { scope: 'create-order.razorpay_failed', eventSlug: slug, passId })
    return NextResponse.json(
      { error: 'Failed to create payment order. Please try again.' },
      { status: 502 },
    )
  }

  // ── 9. Persist payment intent (authoritative data for verify-payment) ──────
  // M3: If this write fails, the Razorpay order is orphaned. Log all identifiers
  //     so the order can be voided manually. Razorpay orders expire after 15 min
  //     if no payment is captured, limiting the blast radius.
  try {
    await createPaymentIntent({
      orderId,
      eventSlug:    slug,
      passId,
      passName,
      passCapacity,
      eventName,
      organizerUid: event.uid,
      amount:       amountPaise,
      currency:     'INR',
      attendee: {
        name:          attendee.name.trim(),
        email:         normEmail,
        // RD-PAY-P0-1: OMITTED when the attendee gave no phone. This was
        // `phone: attendee.phone?.trim() || undefined`, and an explicit `undefined` makes
        // the Admin SDK reject the ENTIRE write. Absent and undefined read back the same,
        // so nothing downstream changes.
        ...(attendee.phone?.trim() ? { phone: attendee.phone.trim() } : {}),
        // RD-RT4.0: sanitised — unknown keys never reach the payment intent either.
        formResponses: safeResponses as Record<string, unknown>,
      },
      // RD-PAY-P0-1: GUEST CHECKOUT. `uid` is optional by design — it is set only when a
      // valid Firebase ID token was presented (step 1). It was previously passed
      // unconditionally, so every signed-out attendee sent `uid: undefined` and the write
      // threw, producing "Failed to persist payment record. Please try again." The field is
      // now simply absent for guests; a uid is NEVER fabricated. Signed-in attendees are
      // unaffected — `uid` is a non-empty string, so it is persisted exactly as before.
      ...(uid ? { uid } : {}),
      ...(inviteCode?.trim() ? { inviteCode: inviteCode.trim() } : {}),
      ...(appliedCouponCode ? {
        couponCode:     appliedCouponCode,
        // Both are typed optional on CouponValidationResult (the route asserts them with
        // `!`), so they are guarded here for the same reason as `uid` rather than trusting
        // the assertion. On today's valid-coupon path both are always present.
        ...(couponDocId    !== undefined ? { couponDocId }    : {}),
        ...(discountAmount !== undefined ? { discountAmount } : {}),
        originalAmount: originalAmountPaise,
      } : {}),
      // RD-PAY-P0-2 — stored so an intent can be traced back to the attempt that made it.
      ...(idempotencyKey ? { idempotencyKey } : {}),
      // RD-PAYMENT-02 Phase 4 — canonical fee breakdown (present only when the pricing
      // engine is enabled). Additive; `amount` above is unchanged and remains the charge.
      ...(financials ? { financials } : {}),
    })
  } catch (err) {
    captureFinancialError(err, { scope: 'create-order.intent_write_failed', detail: 'orphaned Razorpay order', orderId, eventSlug: slug, passId, amount: amountPaise })
    return NextResponse.json(
      { error: 'Failed to persist payment record. Please try again.' },
      { status: 500 },
    )
  }

  // ── 9b. RD-PAY-P0-2: point this attempt at the order it just minted ────────
  //
  // AFTER the intent write, so the claim can never reference an order with no intent
  // behind it (verify-payment would 404 on that). `create()` loses to a concurrent
  // request and defers to the winner; a supersede replaces the stale pointer, and is only
  // reached once findCapturedRegistrationPayment has confirmed the old order holds no money.
  //
  // Best-effort: a claim-write failure must NOT fail a checkout whose order and intent are
  // both already valid. The worst case is the pre-fix behaviour for this one attempt, and
  // the client-side guard still refuses to re-pay after a captured payment.
  if (claimId) {
    const settled = await claimPaymentAttempt(claimId, { orderId, eventSlug: slug }, { replace: supersedingClaim })
      .catch(err => {
        captureFinancialError(err, { scope: 'create-order.attempt_claim_failed', detail: 'non-fatal; order + intent are valid', orderId, claimId })
        return null
      })
    // Lost a race: another request already owns this attempt. Hand back ITS order so the
    // attendee is shown exactly one payable order. Ours stays unpaid and expires.
    if (settled && settled.orderId !== orderId) {
      const winner = await getPaymentIntent(settled.orderId).catch(() => null)
      if (winner) {
        return NextResponse.json({
          orderId: settled.orderId, amount: winner.amount, currency: 'INR',
          keyId: RAZORPAY_KEY_ID, reused: true,
          ...(winner.financials ? { financials: winner.financials } : {}),
        })
      }
    }
  }

  return NextResponse.json({
    orderId,
    amount:   amountPaise,
    currency: 'INR',
    keyId:    RAZORPAY_KEY_ID,
    // RD-PAYMENT-05 B1: return the canonical fee breakdown so the checkout can show the
    // attendee EXACTLY what they will pay before Razorpay opens. Present only when the
    // pricing engine ran (attendee_pays); absent under organizer_pays → response unchanged.
    // financials.chargeAmountPaise === amount above (same object) → display == order == ledger.
    ...(financials ? { financials } : {}),
  })
}
